export PREFERRED_TEXT_EDITOR="`which dit`"

alias d="dit $1"
alias n="nano $1"
alias s="subl $1"
alias a="atom $1"
alias c="chromium-browser $1"
alias g="git $1"
alias r="nautilus $1"
alias ma="$PREFERRED_TEXT_EDITOR ~/.bashrc"

alias gclo="git clone $1"
alias gb="git branch"
alias gc="git checkout $1"
alias grom="git reset origin/master"
alias gac="git add -A; git commit -m $1"